### ISSUE TITLE
How to support text-only dataset (GPTDataset)?

### ISSUE THREAD

**Issue by leondada** [NVIDIA/Megatron-Energon#28]
How to support text-only dataset (GPTDataset)?

**Comment by voegtlel** [comment]
Hey @leondada,

for now, Energon primarily focuses on multi-modal data, e.g. text combined with image(s). For Text-only, there is the optimized data loader from the Megatron-Core repository: https://github.com/NVIDIA/Megatron-LM/tree/main/megatron/core/datasets which also includes a few twists for effective randomized training. These are not (yet) implemented in Energon. Also, you should expect better speed with the specialized loader, if that is an issue for you.

Nevertheless, you can use Energon for text-only data. For that you'd need to create a webdataset containing your .txt files for your samples. Prepare that dataset using the prepare command, using the TextDataset type, then you should be able to get started :slightly_smiling_face: We don't have a full recipe for that yet

**Comment by philipp-fischer** [comment]
If there is no more feedback on this, I think we should close the issue soon

**Comment by philipp-fischer** [comment]
Closing this (stale)
