### ISSUE TITLE
Image loading in binary format with sample_loader.py in energon v4.0.0

### ISSUE THREAD

**Issue by dhkim0225** [NVIDIA/Megatron-Energon#35]
I've encountered an issue with the image loading behavior in energon v4.0.0, specifically when using sample_loader.py. Here are the details:

## Current Behavior
In energon v4.0.0, when using sample_loader.py, images are being decoded during the loading process.

## Previous Behavior
In energon v3.0.1, sample_loader.py used to load images in binary format.

## Impact
This change affects my workflow as I use OpenCV to perform various image transformations. The current decoded image loading method is not suitable for my needs.

## Question
Is there a way to load images in binary format using sample_loader.py in energon v4.0.0, similar to how it worked in v3.0.1?

## Additional Context
Loading images in binary format is crucial for my image processing pipeline, as it allows for more flexibility when working with OpenCV transformations.
Any guidance on how to achieve binary image loading in energon v4.0.0 would be greatly appreciated. If this is not currently possible, I would like to request this feature to be added or the previous functionality to be restored.
Thank you for your attention to this matter.

**Comment by philipp-fischer** [comment]
Hi @dhkim0225.
Decoding images during loading should be the default for both v3.0.1 and also v4.0.0. May I ask what kind of images (extension) you are using?

In any case, you can always disable that behavior by passing `auto_decode=False` as an argument to `get_train_dataset()`

**Comment by philipp-fischer** [comment]
I don't know your exact use case, but you may also want to check out crude data: https://nvidia.github.io/Megatron-Energon/advanced_dataformat.html#crude-data-and-how-to-cook-it

**Comment by dhkim0225** [comment]
I am using TIFF format files that contain multiple images. I wanted to report that all issues have been resolved by using the `auto_decode=False` parameter as you suggested. Thank you for your help!

> Decoding images during loading should be the default for both v3.0.1 and also v4.0.0.

When defining a custom `sample_loader.py`,
  without defining custom dataset (`Sample` class), 
  without specifying any argument for `auto_decode`, 
version 3.0.1 is reading the images in binary format.

The suggested solution of using `auto_decode=False` has successfully addressed this issue, allowing proper handling of multi-page TIFF files in our custom dataset.

Once again, thank you for your support and for providing this solution.

**Comment by philipp-fischer** [comment]
Ok thanks for the details. The reason could lie in the WebDataset decoder that we depend on. It may be that the old one did not support TIFF and the new one does. But great to hear it's solved now.
